#!/usr/bin/env python3
"""Diagnose compact off-network traces without changing or deleting VED rows."""
from __future__ import annotations
import argparse, json, shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import numpy as np
import pandas as pd
import yaml

def load(path:Path)->Any:return json.loads(path.read_text(encoding="utf-8"))
def dump(path:Path,value:Any)->None:path.write_text(json.dumps(value,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument("--config",type=Path,default=Path(r"configs/rnee_build/trajectory_build_off_network_diagnostic.yaml"));args=ap.parse_args();cfg=yaml.safe_load(args.config.read_text(encoding="utf-8"));pointer=load(Path(cfg["map_pointer"]));manifest=load(Path(pointer["manifest"]));metric_frames=[];trip_frames=[]
    for item in manifest["partitions"]:
        points=pd.read_parquet(item["pointer"]["matched_points"],columns=["pilot_trip_id","is_coordinate_update","latitude_raw","longitude_raw"]);updates=points[points["is_coordinate_update"]].copy();metric_frames.append(updates.groupby("pilot_trip_id").agg(latitude_min=("latitude_raw","min"),latitude_max=("latitude_raw","max"),latitude_mean=("latitude_raw","mean"),longitude_min=("longitude_raw","min"),longitude_max=("longitude_raw","max"),coordinate_update_count=("pilot_trip_id","size")).reset_index());trip_frames.append(pd.read_parquet(item["pointer"]["trip_summary"]))
    metrics=pd.concat(metric_frames,ignore_index=True);trips=pd.concat(trip_frames,ignore_index=True);north_south=(metrics["latitude_max"]-metrics["latitude_min"])*111320.0;east_west=(metrics["longitude_max"]-metrics["longitude_min"])*111320.0*np.cos(np.radians(metrics["latitude_mean"]));metrics["raw_bbox_diagonal_m"]=np.hypot(north_south,east_west);frame=trips.merge(metrics,on="pilot_trip_id",how="left",validate="one_to_one");rule=cfg["candidate_rule"];frame["compact_off_network_abstention_candidate"]=frame["has_route_discontinuity"].eq(bool(rule["require_route_discontinuity"]))&(frame["distance_p95_m"]>float(rule["trip_distance_p95_m_min_exclusive"]))&(frame["raw_bbox_diagonal_m"]<=float(rule["raw_coordinate_update_bbox_diagonal_m_max"]));candidates=frame[frame["compact_off_network_abstention_candidate"]].copy()
    quality_check=pd.read_csv(cfg["quality_check_form"]);quality_check_metrics=quality_check.merge(frame[["pilot_trip_id","raw_bbox_diagonal_m","compact_off_network_abstention_candidate"]],on="pilot_trip_id",how="left",validate="one_to_one");labeled=quality_check_metrics[quality_check_metrics["quality_rating"].notna()&quality_check_metrics["quality_rating"].ne("")];incorrect=labeled["quality_rating"].eq("incorrect");candidate=labeled["compact_off_network_abstention_candidate"].astype(bool);unlabeled_controls=quality_check_metrics[quality_check_metrics["quality_rating"].isna()|quality_check_metrics["quality_rating"].eq("")]
    stamp=datetime.now().strftime("%Y%m%d_%H%M%S");out=Path(cfg["output_root"])/f"{cfg['run_name_prefix']}_{stamp}";out.mkdir(parents=True);shutil.copy2(args.config,out/"run_config.yaml");candidate_cols=["source_file","VehId","Trip","pilot_trip_id","raw_point_count","request_point_count","matched_coverage","edge_association_coverage","distance_p95_m","has_route_discontinuity","raw_bbox_diagonal_m","coordinate_update_count","compact_off_network_abstention_candidate"];candidates[candidate_cols].to_csv(out/"compact_off_network_abstention_candidates.csv",index=False);quality_check_metrics.to_csv(out/"quality_1_diagnostic_metrics.csv",index=False)
    summary={"experiment":"TRAJECTORY_BUILD","stage":"compact_off_network_trace_diagnostic","status":"PASS_TRAJECTORY_BUILD_OFF_NETWORK_DIAGNOSTIC_CANDIDATE_ONLY","completed_at_utc":datetime.now(timezone.utc).isoformat(),"rule":rule,"full_trip_count":len(frame),"candidate_trip_count":len(candidates),"candidate_trip_rate":len(candidates)/len(frame),"candidate_raw_row_count":int(candidates["raw_point_count"].sum()),"candidate_raw_row_rate":float(candidates["raw_point_count"].sum()/frame["raw_point_count"].sum()),"quality_1_labeled_count":len(labeled),"quality_1_incorrect_count":int(incorrect.sum()),"quality_1_incorrect_captured":int((incorrect&candidate).sum()),"quality_1_incorrect_recall":float((incorrect&candidate).sum()/incorrect.sum()),"quality_1_nonincorrect_flagged":int(((~incorrect)&candidate).sum()),"quality_1_nonincorrect_count":int((~incorrect).sum()),"unlabeled_random_highest_control_count":len(unlabeled_controls),"unlabeled_random_highest_control_flagged":int(unlabeled_controls["compact_off_network_abstention_candidate"].sum()),"rows_deleted":0,"production_data_modified":False,"claim_boundary":"Quality check-informed candidate for road-semantic abstention, not a validated release rule. Requires fresh Quality check 1 rerating of candidates and unchanged controls.","output_directory":str(out)};dump(out/"off_network_diagnostic_summary.json",summary)
    report=out/"TRAJECTORY_BUILD_COMPACT_OFF_NETWORK_DIAGNOSTIC.md";report.write_text("# TRAJECTORY_BUILD compact off-network diagnostic\n\n"+"\n".join([f"- Status: `{summary['status']}`",f"- Quality check 1 labels: {len(labeled)}; incorrect: {int(incorrect.sum())}.",f"- Candidate captures: {summary['quality_1_incorrect_captured']}/{summary['quality_1_incorrect_count']} incorrect; labeled nonincorrect flagged: {summary['quality_1_nonincorrect_flagged']}/{summary['quality_1_nonincorrect_count']}.",f"- Unlabeled random/highest controls flagged: {summary['unlabeled_random_highest_control_flagged']}/{summary['unlabeled_random_highest_control_count']}.",f"- Full-corpus candidates: {len(candidates):,}/{len(frame):,} trips and {summary['candidate_raw_row_count']:,} raw rows.","- Interpretation: preserve rows but withhold road semantics for candidate traces only after fresh validation; do not delete trips or substitute surrounding-road semantics."])+"\n",encoding="utf-8")
    latest={"status":summary["status"],"summary":str(out/"off_network_diagnostic_summary.json"),"report":str(report),"candidates":str(out/"compact_off_network_abstention_candidates.csv"),"quality_1_metrics":str(out/"quality_1_diagnostic_metrics.csv"),"output_directory":str(out)};dump(Path(cfg["output_root"])/f"{cfg['latest_prefix']}_latest_pointer.json",latest);print(json.dumps(summary,ensure_ascii=False,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
