#!/usr/bin/env python3
"""Build Quality check 1-only maps for compact off-network abstention candidates."""
from __future__ import annotations
import argparse, gc, html, importlib.util, json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import pandas as pd

HERE=Path(__file__).resolve().parent
SPEC=importlib.util.spec_from_file_location("manual_qa",HERE/"08_build_map_match_manual_qa.py");MOD=importlib.util.module_from_spec(SPEC);assert SPEC.loader is not None;SPEC.loader.exec_module(MOD)
def load(path:Path)->Any:return json.loads(path.read_text(encoding="utf-8"))
def dump(path:Path,value:Any)->None:path.write_text(json.dumps(value,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument("--diagnostic-pointer",type=Path,default=Path(r"results/trajectory_build_off_network_diagnostic_latest_pointer.json"));ap.add_argument("--map-pointer",type=Path,default=Path(r"results/trajectory_build_map_match_production_latest_pointer.json"));ap.add_argument("--network-pointer",type=Path,default=Path(r"results/network_freeze_latest_network_pointer.json"));ap.add_argument("--quality-check-form",type=Path,default=Path(r"results/trajectory_build_manual_spatial_qa_20260717_183448\manual_quality_check_form.csv"));ap.add_argument("--trip-summary",type=Path,default=Path(r"results/trajectory_build_manual_qa_staging_20260717_183440\trip_summary.parquet"));ap.add_argument("--output-root",type=Path,default=Path(r"results/rnee_build"));args=ap.parse_args();diag=load(args.diagnostic_pointer);candidates=pd.read_csv(diag["candidates"]);quality_check=pd.read_csv(args.quality_check_form);trip_lookup=pd.read_parquet(args.trip_summary,columns=["pilot_trip_id","source_file"]);quality_check=quality_check.merge(trip_lookup,on="pilot_trip_id",how="left",validate="one_to_one");missed=quality_check[(quality_check["quality_rating"]=="incorrect")&(~quality_check["pilot_trip_id"].isin(candidates["pilot_trip_id"]))].copy();missed=missed[["source_file","VehId","Trip","pilot_trip_id","matched_coverage","edge_association_coverage","distance_p95_m","has_route_discontinuity"]];missed["raw_bbox_diagonal_m"]=pd.NA;missed["validation_category"]="known_incorrect_not_candidate";candidates["validation_category"]="abstention_candidate";selected=pd.concat([candidates,missed],ignore_index=True,sort=False);selected_ids=set(selected["pilot_trip_id"]);pointer=load(args.map_pointer);manifest=load(Path(pointer["manifest"]));point_frames=[]
    for item in manifest["partitions"]:
        ids=selected_ids&set(selected.loc[selected["source_file"]==item["source_file"],"pilot_trip_id"])
        if ids:point_frames.append(pd.read_parquet(item["pointer"]["matched_points"],filters=[("pilot_trip_id","in",sorted(ids))]))
    points=pd.concat(point_frames,ignore_index=True);network=load(args.network_pointer);roads={snapshot:MOD.read_historical_roads(Path(path)) for snapshot,path in network["cropped_pbfs"].items()};stamp=datetime.now().strftime("%Y%m%d_%H%M%S");out=args.output_root/f"trajectory_build_off_network_candidate_qa_{stamp}";maps=out/"maps";geojson=out/"geojson";maps.mkdir(parents=True);geojson.mkdir();rows=[];cards=[]
    selected=selected.sort_values(["validation_category","source_file","VehId","Trip"]).reset_index(drop=True)
    for index,row in enumerate(selected.itertuples(index=False),start=1):
        audit=f"TRAJECTORY_BUILD-OFFNET-{index:03d}";trip_points=points[points["pilot_trip_id"]==row.pilot_trip_id].sort_values("point_index");snapshot=trip_points["osm_snapshot_id"].iloc[0];png=f"{audit}_{row.validation_category}.png";geo=f"{audit}_{row.validation_category}.geojson";title=f"{audit} | {row.validation_category} | Veh {int(row.VehId)}, Trip {int(row.Trip)}\n{snapshot} | coverage={float(row.matched_coverage):.3f}, p95={float(row.distance_p95_m):.1f} m";MOD.plot_trip(trip_points,roads[snapshot],maps/png,title);dump(geojson/geo,MOD.feature_collection(trip_points));rows.append({"audit_id":audit,"validation_category":row.validation_category,"source_file":row.source_file,"pilot_trip_id":row.pilot_trip_id,"VehId":int(row.VehId),"Trip":int(row.Trip),"matched_coverage":row.matched_coverage,"distance_p95_m":row.distance_p95_m,"raw_bbox_diagonal_m":row.raw_bbox_diagonal_m,"map_png":f"maps/{png}","geojson":f"geojson/{geo}","quality_rating":"","quality_notes":""});cards.append(f"<article><a href='maps/{html.escape(png)}'><img loading='lazy' src='maps/{html.escape(png)}'></a><p><b>{audit}</b> | {row.validation_category} | Veh {int(row.VehId)}, Trip {int(row.Trip)}</p></article>")
    form=out/"quality_1_off_network_validation.csv";pd.DataFrame(rows).to_csv(form,index=False,encoding="utf-8-sig");(out/"index.html").write_text("<!doctype html><html lang='zh-CN'><head><meta charset='utf-8'><title>TRAJECTORY_BUILD 非道路轨迹弃权质量确认</title><style>body{font-family:Arial;margin:20px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:18px}article{border:1px solid #ddd;padding:8px}img{width:100%}</style></head><body><h1>TRAJECTORY_BUILD 非道路/停车场轨迹弃权质量确认</h1><p>仅填写 quality_rating：abstain=应停止赋予道路语义；retain=应保留道路匹配；uncertain=无法判定。</p><main>"+"\n".join(cards)+"</main></body></html>\n",encoding="utf-8");(out/"README.md").write_text("# TRAJECTORY_BUILD off-network candidate validation\n\nQuality check all maps and fill only `quality_rating` with `abstain`, `retain`, or `uncertain`. `abstain` means the raw VED trace is mainly off-network, in an open lot/parking area, or otherwise should not inherit surrounding-road semantics. No row or trip will be deleted.\n",encoding="utf-8");summary={"experiment":"TRAJECTORY_BUILD","stage":"off_network_candidate_manual_qa","status":"REQUIRES_QUALITY_CHECK1_OFF_NETWORK_VALIDATION","created_at_utc":datetime.now(timezone.utc).isoformat(),"candidate_count":len(candidates),"known_incorrect_not_candidate_count":len(missed),"audit_count":len(rows),"quality_rating_column":"quality_rating","allowed_ratings":["abstain","retain","uncertain"],"secondary_quality_check_used":False,"production_data_modified":False,"quality_check_form":str(form),"index_html":str(out/"index.html"),"output_directory":str(out)};dump(out/"off_network_candidate_qa_summary.json",summary);dump(args.output_root/"trajectory_build_off_network_candidate_qa_latest_pointer.json",{"status":summary["status"],"summary":str(out/"off_network_candidate_qa_summary.json"),"quality_check_form":str(form),"index_html":str(out/"index.html"),"output_directory":str(out)});roads.clear();gc.collect();print(json.dumps(summary,ensure_ascii=False,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
